### ISSUE TITLE
Some questions during installing the environment

### ISSUE THREAD

**Issue by mrayur** [sisl/ngsim_env#31]
Hi all,

I tried to install the packages and dependencies by the provided "environment.yml", but it seems there is no package python3.5.2 and numpy1.12.0.

**(base) john@john-virtual-machine:~/rllab$ conda env create -f environment.yml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - python==3.5.2
  - numpy==1.12.0**

Then I tried to manually install all packages, errors occurred when installing the 'scipy' and 'numba':

**Collecting scipy
  Using cached https://files.pythonhosted.org/packages/53/10/776750d57ade26522478a92a2e14035868624a6a62f4157b0cc5abd4a980/scipy-1.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gyfx04gc/scipy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.6 required.")
    RuntimeError: Python version >= 3.6 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gyfx04gc/scipy/
You are using pip version 8.1.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.**

So should I install the python3.6 or appoint a version of scipy and numba.

Looking forward to your insight, any kind of help would be appreciated! 

Thanks and regards,
John

**Comment by MaximeBouton** [comment]
@raunakbh92 @djp42

**Comment by mengyuest** [comment]
Hi John, I am able to run PS-GAIL with my own simulator (though not decent performance).  Here is the installation process (may be not elegant, but it follows my debugging process):

```
conda create -n pg2 python==3.6.12 tensorflow-gpu==1.12.0 numpy==1.16.3
conda activate pg2

cd ../rllab && python setup.py develop

conda install path
pip install python-dateutil
pip install joblib==0.11 ## Because of the naming issue for MemmappingPool (https://github.com/rll/rllab/issues/240)
conda install theano
pip install pyprind
pip install cached-property
conda install matplotlib tqdm
```

And [here](https://gist.github.com/mengyuest/b765837ccd80b50a8e9e0949d1eb9db0) is my output for `conda list`. Hope this helps. 
(I am still struggling with installing the NGSim simulator and please let me know if you find a good way to make it work. Thanks)
